const moodMap = {
    happy: {
      range_max: 3,
      range_min: 2,
      genres: [
        "pop",
        "dance",
        "disco",
        "happy",
        "upbeat",
        "funk",
        "salsa",
        "reggae",
        "party",
        "summer",
        "latin",
      ],
    },
    cheerful: {
      range_max: 1,
      range_min: 1,
      genres: [
        "pop",
        "dance",
        "happy",
        "upbeat",
        "indie-pop",
        "reggae",
        "j-pop",
        "k-pop",
        "ska",
        "salsa",
        "summer",
        "latin",
      ],
    },
    calm: {
      range_max: 1,
      range_min: -1,
      genres: [
        "acoustic",
        "chill",
        "classical",
        "jazz",
        "folk",
        "indie",
        "indie-pop",
        "ambient",
        "blues",
        "new-age",
      ],
    },
    sad: {
      range_max: -2,
      range_min: -3,
      genres: ["sad", "emo", "singer-songwriter", "indie", "slow", "ballad"],
    },
    energetic: {
      range_max: 3,
      range_min: 2,
      genres: [
        "rock",
        "hard-rock",
        "metal",
        "punk",
        "pop-punk",
        "alternative",
        "indie",
        "indie-rock",
        "metalcore",
        "post-hardcore",
      ],
    },
    relaxing: {
      range_max: 1,
      range_min: -1,
      genres: ["chill", "ambient", "acoustic", "piano", "instrumental", "jazz"],
    },
    party: {
      range_max: 3,
      range_min: 2,
      genres: [
        "dance",
        "edm",
        "house",
        "techno",
        "electro",
        "trap",
        "pop",
        "reggae",
        "hip-hop",
        "latin",
      ],
    },
    love: {
      range_max: 3,
      range_min: 1,
      genres: [
        "pop",
        "r-n-b",
        "soul",
        "romance",
        "love",
        "ballad",
        "indie-pop",
        "acoustic",
      ],
    },
    focus: {
      range_max: 1,
      range_min: -1,
      genres: ["study", "instrumental", "ambient", "classical", "chill"],
    },
    energetic_sad: {
      range_max: 1,
      range_min: 1,
      genres: [
        "rock",
        "hard-rock",
        "metal",
        "punk",
        "pop-punk",
        "alternative",
        "emo",
        "post-hardcore",
      ],
    },
  };
  
  export default moodMap;